// export const TOGGLE_COLOR = 'TOGGLE_COLOR';
// export const EXAMPLE_REQUEST_START = 'EXAMPLE_REQUEST_START';
// export const EXAMPLE_REQUEST_DATA = 'EXAMPLE_REQUEST_DATA';

export const UPDATE_VIDEOS = 'UPDATE_VIDEOS';
export const SELECT_VIDEO = 'SELECT_VIDEO';
