export const FETCH_VIDEOS = 'FETCH_VIDEOS';
export const UPDATE_VIDEOS = 'UPDATE_VIDEOS';
export const SELECT_VIDEO = 'SELECT_VIDEO';
export const FETCH_VIDEOS_FAILED = 'FETCH_VIDEOS_FAILED';
export const LOGIN = 'LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';
